# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# キャプチャ可能な長さを設定します。
# 例えば8にした場合、8マス先までの相手をクリックして捕まえることができますが、
# 9マス以上先は捕まえることができません。
# 30まで伸ばすことが可能です。それ以上指定すると、釣り糸がきれます。
captureRange: 8

# クラフト可/不可を切り替えます。
enableCraft: true

# キャプチャワイヤーの長さを設定します。
# 例えば3.0にした場合、キャプチャした相手との距離が3マス以下になるまで、
# 引っ張る力が発生します。
wireLength: 3.0

# キャプチャワイヤーの張力を設定します。
# デフォルトは5.0で、小さい値を設定するほど、引っ張る力が大きくなります。
wireTension: 5.0

# 1回の使用で消耗する、耐久度を設定します。
# 0にすれば無制限に使用できます。
durabilityCost: 2
