name: ${project.name}
main: org.bitbucket.ucchy.cr.CaptureRod
version: ${project.version}
author: ucchy
description: ${project.description}
softdepend: [ColorTeaming]

commands:
  capturerod:
    description: ${project.description}
    aliases: [cap]
    usage: |
           /<command> get - Get new CaptureRod.
           /<command> give (player) - Give new CaptureRod.
           /<command> reload - Reload config.yml.
    permission: capturerod.command
    permission-message: You don't have permission "<permission>".

permissions:
  capturerod.command:
    description: CaptureRod command permission.
    default: true
  capturerod.reload:
    description: CaptureRod reload command permission.
    default: op
  capturerod.get:
    description: CaptureRod get command permission.
    default: op
  capturerod.give:
    description: CaptureRod give command permission.
    default: op
  capturerod.action:
    description: CaptureRod action permission.
    default: true
  capturerod.*:
    children:
      capturerod.command: true
      capturerod.reload: true
      capturerod.get: true
      capturerod.give: true
      capturerod.action: true
    description: All of CaptureRod permission.
